AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  GithubOrg: # can also be a regular user
    Type: String
    Default: sankalptambe
  FullRepoName:
    Type: String
    Default: sankalptambe/aws-federation-github-actions

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ExampleGithubRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${FullRepoName}:*"

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList: 
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e
      ClientIdList: 
        - !Sub "https://github.com/${GithubOrg}"

Outputs:
  Role:
    Value: !GetAtt Role.Arn  